version: "3.8"
services:
    react-app:
      stdin_open: true
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
          - '.:/usr/src/app'
          - /usr/src/app/node_modules
      ports:
        - 3000:3000

